Name: Product.api
Host: 0.0.0.0
Port: 0
Timeout: 2000

Auth:
  AccessSecret: # the same as core
  AccessExpire: 259200

CROSConf:
  Address: '*'

Log:
  ServiceName: ProductApiLogger
  Mode: file
  Path: /home/data/logs/Product/api
  Level: info
  Compress: false
  KeepDays: 7
  StackCoolDownMillis: 100

Prometheus:
  Host: 0.0.0.0
  Port: 4000
  Path: /metrics


